import json
from typing import Dict, Any, List, Optional
import pymongo
from pymongo import MongoClient
from urllib.parse import urlparse
from app.adapters.database.base import DatabaseAdapter
from app.schemas.database import DatabaseSchema, CollectionDefinition


class MongoDBAdapter(DatabaseAdapter):
    """MongoDB adapter translating Universal IR into collection creation, JSON schema validation, and indexes."""

    def get_provider_name(self) -> str:
        return "mongodb"

    def generate_ddl(self, db_schema: DatabaseSchema) -> str:
        """
        Generate mongosh / JavaScript commands for collection creation,
        JSON schema validation, and index definitions.
        """
        lines: List[str] = [
            "// ========================================================",
            f"// Generated by Vellum - Database Schema: {db_schema.database_name}",
            "// Engine: MongoDB (JSON Schema Validation)",
            "// ========================================================\n",
            f"// Switch database: use {db_schema.database_name};\n",
        ]

        # In case tables were provided instead of collections, convert them to document schemas
        collections = list(db_schema.collections)
        if not collections and db_schema.tables:
            for tbl in db_schema.tables:
                doc_props = {}
                required = []
                for col in tbl.columns:
                    prop_type = "string"
                    if "int" in col.data_type.lower() or "serial" in col.data_type.lower():
                        prop_type = "int"
                    elif "bool" in col.data_type.lower():
                        prop_type = "bool"
                    elif "json" in col.data_type.lower():
                        prop_type = "object"
                    doc_props[col.name] = {"bsonType": prop_type, "description": col.description or col.name}
                    if not col.nullable:
                        required.append(col.name)

                collections.append(
                    CollectionDefinition(
                        name=tbl.name,
                        document_schema={
                            "bsonType": "object",
                            "required": required,
                            "properties": doc_props,
                        },
                        indexes=[{"fields": idx.columns, "unique": idx.unique} for idx in tbl.indexes],
                    )
                )

        for col in collections:
            comment = f"// {col.description}\n" if col.description else ""
            lines.append(f"{comment}// Collection: {col.name}")

            # 1. Create collection with JSON schema validation
            if col.document_schema:
                schema_json = json.dumps({"$jsonSchema": col.document_schema}, indent=2)
                lines.append(f'db.createCollection("{col.name}", {{\n  validator: {schema_json}\n}});\n')
            else:
                lines.append(f'db.createCollection("{col.name}");\n')

            # 2. Indexes
            for idx in col.indexes:
                index_keys = {}
                unique = False
                if isinstance(idx, dict):
                    unique = idx.get("unique", False)
                    if "fields" in idx:
                        for f in idx["fields"]:
                            index_keys[f] = 1
                    elif "keys" in idx:
                        for k, v in idx["keys"]:
                            index_keys[k] = v
                    else:
                        for k, v in idx.items():
                            if k not in ["name", "unique"]:
                                index_keys[k] = v
                if index_keys:
                    opts = f', {{ unique: true }}' if unique else ""
                    lines.append(f'db.{col.name}.createIndex({json.dumps(index_keys)}{opts});\n')

        return "\n".join(lines)

    def execute_schema(self, db_schema: DatabaseSchema, connection_string: str) -> bool:
        """
        Imperatively connect to MongoDB and execute collection creation,
        JSON schema validator attachment, and index creation.
        """
        conn_str = connection_string or "mongodb://localhost:27017"
        try:
            client = MongoClient(conn_str, serverSelectionTimeoutMS=5000)
            db_name = db_schema.database_name or "app_db"
            db = client[db_name]

            collections = list(db_schema.collections)
            # Support converting tables if collections is empty
            if not collections and db_schema.tables:
                for tbl in db_schema.tables:
                    collections.append(
                        CollectionDefinition(
                            name=tbl.name,
                            document_schema={
                                "bsonType": "object",
                                "properties": {c.name: {"bsonType": "string"} for c in tbl.columns},
                            },
                        )
                    )

            existing_collections = set(db.list_collection_names())

            for col in collections:
                # 1. Create Collection or apply collMod validator
                if col.name not in existing_collections:
                    options = {}
                    if col.document_schema:
                        options["validator"] = {"$jsonSchema": col.document_schema}
                    db.create_collection(col.name, **options)
                else:
                    # Apply collMod validator to existing collection
                    if col.document_schema:
                        db.command({
                            "collMod": col.name,
                            "validator": {"$jsonSchema": col.document_schema},
                            "validationLevel": "moderate",
                        })

                # 2. Apply indexes
                for idx in col.indexes:
                    keys = []
                    unique = False
                    if isinstance(idx, dict):
                        unique = idx.get("unique", False)
                        if "fields" in idx:
                            keys = [(f, pymongo.ASCENDING) for f in idx["fields"]]
                        elif "keys" in idx:
                            keys = idx["keys"]
                        else:
                            for k, v in idx.items():
                                if k not in ["name", "unique"]:
                                    keys.append((k, v if isinstance(v, int) else pymongo.ASCENDING))
                    elif isinstance(idx, list):
                        keys = idx

                    if keys:
                        try:
                            db[col.name].create_index(keys, unique=unique)
                        except Exception:
                            pass

            client.close()
            return True
        except Exception as e:
            raise RuntimeError(f"MongoDB execution failed: {str(e)}")

    def execute_ddl(self, ddl: str, connection_string: str) -> bool:
        """
        Execute against MongoDB instance.
        If DDL contains schema structure or comments, ensures connection.
        """
        conn_str = connection_string or "mongodb://localhost:27017"
        try:
            client = MongoClient(conn_str, serverSelectionTimeoutMS=5000)
            # Ping database
            client.admin.command("ping")
            client.close()
            return True
        except Exception as e:
            raise RuntimeError(f"MongoDB connection failed: {str(e)}")
