import re
from typing import Dict, Any, List, Optional
import pymysql
from urllib.parse import urlparse
from app.adapters.database.base import DatabaseAdapter
from app.schemas.database import DatabaseSchema, TableDefinition, ColumnDefinition


class MySQLAdapter(DatabaseAdapter):
    """MySQL DDL generator and execution adapter supporting InnoDB and utf8mb4."""

    def get_provider_name(self) -> str:
        return "mysql"

    def generate_ddl(self, db_schema: DatabaseSchema) -> str:
        statements: List[str] = [
            "-- ========================================================",
            f"-- Generated by Vellum - Database Schema: {db_schema.database_name}",
            "-- Engine: MySQL (InnoDB / utf8mb4)",
            "-- ========================================================\n",
        ]

        # Generate Tables
        for table in db_schema.tables:
            statements.append(self._generate_table_ddl(table))

        # Separate Index statements if any additional standalone indexes exist
        for table in db_schema.tables:
            for idx in table.indexes:
                cols = ", ".join(f"`{c}`" for c in idx.columns)
                unique_str = "UNIQUE " if idx.unique else ""
                statements.append(
                    f"CREATE {unique_str}INDEX `{idx.name}` ON `{table.name}` ({cols});\n"
                )

        return "\n".join(statements)

    def _map_column_type(self, col: ColumnDefinition) -> str:
        raw_type = col.data_type.strip().lower()

        # Rule 1: integer / serial with auto_increment / primary_key
        if raw_type in ["serial", "auto_increment"] or (
            col.primary_key and raw_type in ["int", "integer", "bigint", "serial"]
        ):
            if "big" in raw_type:
                return "BIGINT AUTO_INCREMENT PRIMARY KEY"
            return "INT AUTO_INCREMENT PRIMARY KEY"

        # Rule 2: varchar requires explicit length (default 255)
        if raw_type.startswith("varchar"):
            if "(" not in raw_type:
                return "VARCHAR(255)"
            return raw_type.upper()

        if raw_type in ["string", "char"]:
            return "VARCHAR(255)"

        # Rule 3: array types (e.g. text[], int[]) -> JSON
        if "[]" in raw_type or raw_type.endswith("array"):
            return "JSON"

        # Rule 4: timestamp -> TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        if raw_type == "timestamp":
            if not col.default:
                return "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            return "TIMESTAMP"

        if raw_type in ["text", "longtext", "mediumtext"]:
            return raw_type.upper()

        if raw_type in ["bool", "boolean"]:
            return "TINYINT(1)"

        if raw_type in ["json", "jsonb"]:
            return "JSON"

        if raw_type in ["float", "double", "decimal", "numeric"]:
            return raw_type.upper()

        return raw_type.upper()

    def _generate_table_ddl(self, table: TableDefinition) -> str:
        lines: List[str] = []
        pk_columns = []

        for col in table.columns:
            type_str = self._map_column_type(col)
            is_inline_pk = "PRIMARY KEY" in type_str
            if col.primary_key and not is_inline_pk:
                pk_columns.append(f"`{col.name}`")

            parts = [f"  `{col.name}` {type_str}"]

            if not is_inline_pk:
                if not col.nullable and not col.primary_key:
                    parts.append("NOT NULL")
                if col.unique and not col.primary_key:
                    parts.append("UNIQUE")
                if col.default and "DEFAULT" not in type_str:
                    parts.append(f"DEFAULT {col.default}")

            if col.references and "(" in col.references:
                # inline reference
                ref_parts = col.references.replace(")", "").split("(")
                if len(ref_parts) == 2:
                    ref_tbl, ref_col = ref_parts[0].strip(), ref_parts[1].strip()
                    parts.append(f"REFERENCES `{ref_tbl}` (`{ref_col}`)")

            lines.append(" ".join(parts))

        # Explicit composite / non-inline primary keys
        if pk_columns:
            lines.append(f"  PRIMARY KEY ({', '.join(pk_columns)})")

        # Explicit Foreign Keys
        for fk in table.foreign_keys:
            fk_name = fk.name or f"fk_{table.name}_{fk.ref_table}"
            cols = ", ".join(f"`{c}`" for c in fk.columns)
            ref_cols = ", ".join(f"`{c}`" for c in fk.ref_columns)
            on_del = fk.on_delete or "CASCADE"
            on_upd = fk.on_update or "CASCADE"
            lines.append(
                f"  CONSTRAINT `{fk_name}` FOREIGN KEY ({cols}) REFERENCES `{fk.ref_table}` ({ref_cols}) ON DELETE {on_del} ON UPDATE {on_upd}"
            )

        body = ",\n".join(lines)
        comment = f"-- {table.description}\n" if table.description else ""

        # Rule 5: Always append ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        return f"{comment}CREATE TABLE IF NOT EXISTS `{table.name}` (\n{body}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"

    def execute_ddl(self, ddl: str, connection_string: str) -> bool:
        """
        Execute DDL statements against target MySQL database.
        Accepts standard mysql connection string: mysql://user:password@host:port/dbname
        or host:port/user/pass dict/params.
        """
        try:
            # Parse connection string
            if connection_string.startswith("mysql://") or connection_string.startswith("mysql+pymysql://"):
                url = urlparse(connection_string.replace("mysql+pymysql://", "mysql://"))
                host = url.hostname or "localhost"
                port = url.port or 3306
                user = url.username or "root"
                password = url.password or ""
                target_db = url.path.lstrip("/") or "app_db"
            else:
                host = "localhost"
                port = 3306
                user = "root"
                password = ""
                target_db = "app_db"

            try:
                conn = pymysql.connect(
                    host=host,
                    port=port,
                    user=user,
                    password=password,
                    database=target_db,
                    charset="utf8mb4",
                    autocommit=True,
                )
            except pymysql.err.OperationalError as op_err:
                if op_err.args[0] == 1049:  # ER_BAD_DB_ERROR
                    root_conn = pymysql.connect(
                        host=host,
                        port=port,
                        user=user,
                        password=password,
                        charset="utf8mb4",
                        autocommit=True,
                    )
                    with root_conn.cursor() as c:
                        c.execute(f"CREATE DATABASE IF NOT EXISTS `{target_db}`;")
                    root_conn.close()
                    conn = pymysql.connect(
                        host=host,
                        port=port,
                        user=user,
                        password=password,
                        database=target_db,
                        charset="utf8mb4",
                        autocommit=True,
                    )
                else:
                    raise


            with conn.cursor() as cursor:
                raw_statements = ddl.split(";")
                for raw_stmt in raw_statements:
                    lines = [
                        line
                        for line in raw_stmt.splitlines()
                        if not line.strip().startswith("--") and not line.strip().startswith("#")
                    ]
                    stmt = "\n".join(lines).strip()
                    if stmt:
                        cursor.execute(stmt)
            conn.close()
            return True

        except Exception as e:
            raise RuntimeError(f"MySQL DDL execution failed: {str(e)}")
