from typing import Dict, Any, List
from sqlalchemy import create_engine, text
from app.adapters.database.base import DatabaseAdapter
from app.schemas.database import DatabaseSchema, TableDefinition


class PostgreSQLAdapter(DatabaseAdapter):
    """PostgreSQL DDL generator and execution adapter."""

    def get_provider_name(self) -> str:
        return "postgresql"

    def generate_ddl(self, db_schema: DatabaseSchema) -> str:
        statements: List[str] = [
            f"-- ========================================================",
            f"-- Generated by Vellum - Database Schema: {db_schema.database_name}",
            f"-- Engine: PostgreSQL",
            f"-- ========================================================\n"
        ]

        # Extensions
        for ext in db_schema.extensions:
            statements.append(f'CREATE EXTENSION IF NOT EXISTS "{ext}";\n')

        # Tables
        for table in db_schema.tables:
            statements.append(self._generate_table_ddl(table))

        # Indexes
        for table in db_schema.tables:
            for idx in table.indexes:
                cols = ", ".join(f'"{c}"' for c in idx.columns)
                unique_str = "UNIQUE " if idx.unique else ""
                statements.append(
                    f'CREATE {unique_str}INDEX IF NOT EXISTS "{idx.name}" ON "{table.name}" ({cols});\n'
                )

        return "\n".join(statements)

    def _generate_table_ddl(self, table: TableDefinition) -> str:
        lines: List[str] = []
        for col in table.columns:
            parts = [f'  "{col.name}" {col.data_type.upper()}']
            if col.primary_key:
                parts.append("PRIMARY KEY")
            if not col.nullable and not col.primary_key:
                parts.append("NOT NULL")
            if col.unique and not col.primary_key:
                parts.append("UNIQUE")
            if col.default:
                parts.append(f"DEFAULT {col.default}")
            if col.references:
                parts.append(f"REFERENCES {col.references}")
            lines.append(" ".join(parts))

        # Explicit Foreign keys
        for fk in table.foreign_keys:
            fk_name = fk.name or f"fk_{table.name}_{fk.ref_table}"
            cols = ", ".join(f'"{c}"' for c in fk.columns)
            ref_cols = ", ".join(f'"{c}"' for c in fk.ref_columns)
            lines.append(
                f'  CONSTRAINT "{fk_name}" FOREIGN KEY ({cols}) REFERENCES "{fk.ref_table}" ({ref_cols}) ON DELETE {fk.on_delete or "CASCADE"}'
            )

        body = ",\n".join(lines)
        comment = f"-- {table.description}\n" if table.description else ""
        return f'{comment}CREATE TABLE IF NOT EXISTS "{table.name}" (\n{body}\n);\n'

    def execute_ddl(self, ddl: str, connection_string: str) -> bool:
        """Execute DDL statements against target PostgreSQL instance."""
        try:
            engine = create_engine(connection_string)
            with engine.connect() as conn:
                # Split and execute individual statements
                statements = [s.strip() for s in ddl.split(";") if s.strip() and not s.strip().startswith("--")]
                for stmt in statements:
                    conn.execute(text(stmt))
                conn.commit()
            return True
        except Exception as e:
            raise RuntimeError(f"PostgreSQL DDL execution failed: {str(e)}")
